# Generated by Django 5.0.6 on 2024-06-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7)),
                ('contrasena', models.CharField(max_length=10)),
                ('tipo_usuario', models.CharField(choices=[('EPRG', 'Refinacion_gasolina'), ('PRD', 'Refinacion_diesel'), ('PRA', 'Refinacion_aviacion')], default='PRD', max_length=10)),
            ],
        ),
    ]
