# Generated by Django 5.0.6 on 2024-06-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=78)),
                ('litros', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=300)),
                ('hora', models.CharField(max_length=100)),
                ('operador', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('EPRG', 'EPRG'), ('PRD', 'PRD'), ('PRA', 'PRA')], default='PRD', max_length=10),
        ),
    ]
