# Generated by Django 5.0.6 on 2024-07-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_formulario_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7)),
                ('nombre_supervisor', models.CharField(max_length=10)),
                ('apellido_supervisor', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=10)),
                ('tipo_usuario', models.CharField(choices=[('EPRG', 'EPRG'), ('PRD', 'PRD'), ('PRA', 'PRA')], default='PRD', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_usuario',
            field=models.CharField(default='Desconocido', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(default='Desconocido', max_length=10),
        ),
    ]
